### ISSUE TITLE
As an administrator, I would like to see the stock dependencies related to an order item

### ISSUE THREAD

**Issue by kmac420** [kmac420/stock-dependencies-for-woocommerce#15]
For each order line item that has associated stock dependencies, display the dependency and quantity

**Comment by kmac420** [comment]
Proposed format:

<img width="800" alt="Screen Shot 2021-01-18 at 2 09 39 PM" src="https://user-images.githubusercontent.com/474476/104955013-74d54600-5997-11eb-8fa2-8c009da66858.png">

**Comment by rfrancisco87** [comment]
Hi,

Please check my test (sorry it is in portuguese).

I have ordered this product that is a comb (3 products) - https://jmp.sh/Q17GK9g
But in the order backoffice it is not displaying the products list - https://jmp.sh/5FqY43i

There is any way to check if it has any conflict?

Thanks!
